baseurl = "https://marleybuchman.com/"
languageCode = "en-us"
title = "Marley Buchman"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"





[[menu.main]]
    name = "GitHub"
    url = "https://github.com/buchmayne"
    weight = 1
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/buchmayne"
    weight = 2


[params]
    description = "Marley Buchman's personal website"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "avatar.jpeg"
    width = 50
    height = 50
    alt = "Logo"

